# Generated by Django 3.2.16 on 2022-10-30 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('day', models.DateField(primary_key=True, serialize=False)),
                ('boarding', models.IntegerField(blank=True, null=True)),
                ('getoff', models.IntegerField(blank=True, db_column='getOff', null=True)),
            ],
            options={
                'db_table': 'Bus',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Seoulindex',
            fields=[
                ('gu', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('population_over12', models.IntegerField(blank=True, null=True)),
                ('commute_population', models.IntegerField(blank=True, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'SeoulIndex',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Spotposition',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'SpotPosition',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rawroadtraffic',
            fields=[
                ('name', models.OneToOneField(db_column='name', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='plotting.spotposition')),
                ('day', models.DateField()),
                ('vol', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'RawRoadTraffic',
                'managed': False,
            },
        ),
    ]
